# Generated by Django 5.2.5 on 2025-12-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
