# Generated by Django 5.2.5 on 2025-12-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_cost_price_product_markup_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='markup_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
