# Generated by Django 5.2.5 on 2025-12-08 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('pack_weight_grams', models.PositiveIntegerField(default=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'ordering': ['pack_weight_grams', 'name'],
            },
        ),
    ]
